#!/bin/bash


# "file" or "env"
MODE=$1

# a file path or an environment variable name
ITEM=$2


if [[ "$MODE" == "file" ]]; then

    if [ ! -s "$ITEM" ]; then
       echo "no"
       exit 0
    fi
    echo "yes"
    exit 0

elif [[ "$MODE" == "env" ]]; then
    ENV_VARIABLE_NAME=$ITEM
    VALUE="${!ENV_VARIABLE_NAME}"

    if [[ -z "$VALUE" ]]; then
      echo "no"
      exit 0
    fi
    echo "yes"
    exit 0
fi
