#!/bin/bash

TAG=$1
TYPE=${2:-"IP_ADDRESS"}


if [[ $HOSTING_ENV == "vagrant" || $HOSTING_ENV == "lxd" ]]; then
  if [[ $TYPE == "IP_HOSTNAME" ]]; then
    QUERY=".ip_hostnames_by_tag[\"$TAG\"]|join(\" \")"
  else
    QUERY=".ip_addresses_by_tag[\"$TAG\"]|join(\" \")"
  fi
  DATA=$(cat /etc/node-metadata.json | jq -r "$QUERY" 2> /dev/null)
  echo $DATA
  exit 0
fi


# temporary: hostnames aren't returned by go_discover, we'll use node-metadata.json
# todo: query for ip & hostnames with 'gcloud compute instances list'
if [[ $TYPE == "IP_HOSTNAME" ]]; then
  QUERY=".ip_hostnames_by_tag[\"$TAG\"]|join(\" \")"
  DATA=$(cat /etc/node-metadata.json | jq -r "$QUERY" 2> /dev/null)
  echo $DATA
  exit 0
fi

PROJECT_ID=$(metadata_get cluster_service_project_id)
REGION=$(metadata_get region)

NODE_IP_ADDRESSES=$(/usr/local/bin/discover addrs provider=gce project_name="$PROJECT_ID" zone_pattern="$REGION.*" tag_value="$TAG")

echo $NODE_IP_ADDRESSES
